# Generated by Django 4.2.5 on 2023-09-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.IntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('worker', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('stock', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='app.warehouse')),
            ],
        ),
    ]
